name: Broadcaster
main: Broadcaster\Broadcaster
version: 1.5
api: [3.0.0]
load: STARTUP
author: EvolSoft
description: Advanced Broadcasting plugin
website: https://www.evolsoft.tk
commands:
 broadcaster:
  aliases: [bc, broadcast]
  description: Broadcaster commands.
  permission: broadcaster
 sendmessage:
  aliases: [sm, smsg]
  description: Send a message to the specified player (* for all players)
  permission: broadcaster.sendmessage
 sendpopup:
  aliases: [sp, spop]
  description: Send a popup to the specified player (* for all players)
  permission: broadcaster.sendpopup
 sendtitle:
  aliases: [st, stl]
  description: Send a title to the specified player (* for all players)
  permission: broadcaster.sendtitle
permissions:
 broadcaster:
  default: op
  description: Broadcaster permissions tree.
  children:
   broadcaster.info:
    default: op
    description: Let player read info about Broadcaster.
   broadcaster.reload:
    default: op
    description: Let player reload Broadcaster.
   broadcaster.update:
    default: op
    description: Let player update Broadcaster.
   broadcaster.sendmessage:
    default: op
    description: Let player send messages to players with /sendmessage command.
   broadcaster.sendpopup:
    default: op
    description: Let player send popups to players with /sendpopup command.
   broadcaster.sendtitle:
    default: op
    description: Let player send titles to players with /sendtitle command.
